-- Fiche de référence / contre-référence (évacuation du patient pour meilleure
-- prise en charge) — même modèle que la fiche officielle HGF.
CREATE TABLE [fiches_reference] (
    [id]            INT IDENTITY(1,1) NOT NULL,
    [cliniqueId]    INT NOT NULL,
    [passageId]     INT NOT NULL,
    [patientId]     INT NOT NULL,
    [numero]        NVARCHAR(100) NOT NULL,
    [transfertUrgent] BIT,
    [nomPrenoms]    NVARCHAR(1000),
    [age]           NVARCHAR(1000),
    [sexe]          NVARCHAR(1000),
    [numeroSecu]    NVARCHAR(1000),
    [adresseTel]    NVARCHAR(1000),
    [numeroRegistreSig] NVARCHAR(1000),
    [districtSanitaire] NVARCHAR(1000),
    [dateAdmission] DATETIME2,
    [heureAdmission] NVARCHAR(1000),
    [agentNom]      NVARCHAR(1000),
    [agentPrenom]   NVARCHAR(1000),
    [agentContact]  NVARCHAR(1000),
    [institutionReference] NVARCHAR(1000),
    [serviceReference] NVARCHAR(1000),
    [dateHeureDecision] NVARCHAR(1000),
    [diagnostic]    NVARCHAR(1000),
    [examensCliniques] NVARCHAR(1000),
    [antecedentsMedicaux] NVARCHAR(1000),
    [antecedentsChirurgicaux] NVARCHAR(1000),
    [antecedentsGyneco] NVARCHAR(1000),
    [allergie]      NVARCHAR(1000),
    [groupeSanguin] NVARCHAR(1000),
    [motifReference] NVARCHAR(1000),
    [traitementRecu] NVARCHAR(1000),
    [depuisQuand]   NVARCHAR(1000),
    [modeEvacuation] NVARCHAR(1000),
    [modeEvacuationAutre] NVARCHAR(1000),
    [dateHeureDepart] NVARCHAR(1000),
    [contreNomPrenoms] NVARCHAR(1000),
    [contreNumeroDossier] NVARCHAR(1000),
    [contreDateArrivee] NVARCHAR(1000),
    [contreDiagnostic] NVARCHAR(1000),
    [contreHospitalise] BIT,
    [contreTraitement] NVARCHAR(1000),
    [contreMedecin]  NVARCHAR(1000),
    [contreDateSignature] NVARCHAR(1000),
    [etabliParId]    INT,
    [createdAt]      DATETIME2 NOT NULL CONSTRAINT [fiches_reference_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt]      DATETIME2 NOT NULL CONSTRAINT [fiches_reference_updatedAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [fiches_reference_pkey] PRIMARY KEY ([id]),
    CONSTRAINT [fiches_reference_numero_key] UNIQUE ([numero]),
    CONSTRAINT [fiches_reference_cliniqueId_fkey] FOREIGN KEY ([cliniqueId]) REFERENCES [cliniques]([id]),
    CONSTRAINT [fiches_reference_passageId_fkey] FOREIGN KEY ([passageId]) REFERENCES [passages]([id]) ON DELETE CASCADE,
    CONSTRAINT [fiches_reference_patientId_fkey] FOREIGN KEY ([patientId]) REFERENCES [patients]([id]),
    CONSTRAINT [fiches_reference_etabliParId_fkey] FOREIGN KEY ([etabliParId]) REFERENCES [utilisateurs]([id])
);
CREATE INDEX [fiches_reference_patientId_idx] ON [fiches_reference]([patientId]);
